### ISSUE TITLE
Install doesn't work?

### ISSUE THREAD

**Issue by aagrawal05** [Xedecimal/userstyles#1]
How do you compile the .styl files? I tried clicking on the install links, but they just took me to a static .styl file

**Comment by Xedecimal** [comment]
Are you using the Stylus plugin?

Chrome: https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne
Firefox: https://addons.mozilla.org/en-US/firefox/addon/styl-us/

**Comment by aagrawal05** [comment]
Oh great it works perfectly now, thanks so much. Great theme btw.

**Comment by Xedecimal** [comment]
Great. Let me know if anything needs changing or updating
